config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "lifts#index"

  resources :lifts do
    resources :reviews, only: [:new, :create, :show, :index, :destroy]
  end

  resources :users do
    resources :lifts, only: [:destroy]
  end
end

app/models/lift.rb
class Lift < ActiveRecord::Base
  belongs_to :user, required: true
  has_many :reviews, as: :imageable

  geocoded_by :address

  after_validation :geocode

  mount_uploader :photo, PhotoUploader

  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, as: :imageable
  has_many :lifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lifts_controller.rb
  class LiftsController < ApplicationController
  def index
    @lifts = Lift.all
    @markers = Gmaps4rails.build_markers(@lifts) do |lift, marker|
      marker.lat lift.latitude
      marker.lng lift.longitude
    end
  end

  def show
    @lift = Lift.find(params[:id])
    @lift_coordinates = { lat: @lift.latitude, long: @lift.longitude }
  end

  def new
    @lift = Lift.new
  end

  def create
    @lift = Lift.new(lift_params)
    @lift.user = current_user

    if @lift.save
      redirect_to @lift
    else
      render :new
    end
  end

  def destroy
    @lift = Lift.find(params[:id])
    @lift.destroy
   redirect_to lifts_path
  end

  def update
    @lift = Lift.new(lift_params)
    if @lift.save
     redirect_to lift_path(@lift)
    else
     render :edit
    end
  end

  def edit
   @lift = Lift.new
  end

  private

  def lift_params
    params.require(:lift).permit(:name, :address, :photo, :photo_cache)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FloSamProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'shared/nav_bar' %>

  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&sensor=false&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag 'application' %>
  <%= render 'shared/footer' %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/layouts/new.html.erb
new.html.erb

app/views/lifts/_form.html.erb
<%= simple_form_for(@lift) do |f| %>
  <% if @lift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lift.errors.count, "error") %> prohibited this lift from being saved:</h2>

      <ul>
      <% @lift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="form-actions">
           <%= f.button :submit, "Create", id:'log' %>
         </div>


<% end %>

app/views/lifts/banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>L'entretien sans intermédiaire</h1>
    <h1>Louez votre espace de garage</h1>

      <form class="form-inline">
        <div class="form-group">
          <label for="geolocalizeAddress">Votre code postal</label>
            <input type="text" class="form-control" id="geolocalizeAddress" placeholder="59120">
        </div>
      <button type="submit" class="btn btn-primary">Valider</button>
      </form>

  </div>
</div>

app/views/lifts/edit.html.erb
<div class="banner">

 <div class="container">
   <div class="col-xs-12 col-sm-6  col-sm-offset-3">
     <div class="login">

      <h1>Editing Lift</h1>

      <%= render 'form' %>

      <div class="links">

      <%= link_to 'Show', @lift %> |
      <%= link_to 'Back', lifts_path %>

      </div>
      </div>
    </div>
  </div>
</div>

app/views/lifts/index.html.erb
<div class="banner">
 <div class="banner-content">
   <h1>L'entretien sans intermédiaire</h1>
   <h1>Louez votre espace de garage</h1>

   <form class="form-inline">
     <div class="form-group">
       <label for="geolocalizeAddress">Votre code postal</label>
       <input type="text" class="form-control" id="geolocalizeAddress" placeholder="59120">
     </div>
     <button type="submit" class="btn btn-primary">Valider</button>
   </form>
 </div>
</div>

<div class="banner-content">
 <h1>Choisissez un pont</h1>
</div>

<div class="container">
 <div class= "row">
   <div class="col-lg-6 col-sm-6">
     <% @lifts.each do |lift| %>
     <div class= "row">
       <div class="col-lg-12 col-sm-12">
         <!-- <div class= "card"> -->
         <%= cl_image_tag lift.photo, height: 200, width: 400, crop: :fill %>
         <h2><%= link_to lift.name, lift_path(lift)%></h2>
         <h5><%= lift.address%></h5>
         <!-- </div> -->
       </div>
     </div>
     <% end %>
   </div>
   <div class="col-lg-6 col-sm-6 map">
     <div id="map" style="width: 100%; height: 600px;"></div>
   </div>
 </div>
 <div class="row">
   <p><%= link_to 'Ajouter un pont', new_lift_path, {class: "btn-medium"}%></p>
 </div>
</div>

<% content_for(:after_js) do %>
 <%= javascript_tag do %>
   $(document).on('ready', function() {
     handler = Gmaps.build('Google');
     handler.buildMap({ internal: { id: 'map' } }, function(){
       markers = handler.addMarkers(<%= raw @markers.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
     });
   })
 <% end %>
<% end %>

app/views/lifts/new.html.erb
<div class="banner">

 <div class="container">
   <div class="col-xs-12 col-sm-6  col-sm-offset-3">
     <div class="login">
      <h1>Création d'un nouveau pont</h1>

      <%= render 'form' %>

      <div class="links">

      <%= link_to 'Back', lifts_path %>
      </div>



      </div>
    </div>
  </div>
</div>

app/views/lifts/show.html.erb
<div class= "wrapper-grey">
  <div class= "container", style="padding-top: 40px">

    <div class= "row">
      <div class= "col-xs-12 col-sm-12">
        <div class= "col-xs-9 col-sm-9">
          <h2>Réservez votre créneau pour votre pont:</h2>
        </div>
        <div class= "col-xs-3 col-sm-3">
          <%= link_to 'Retour à la liste des ponts', lifts_path, {class: "btn-medium"}%>
        </div>
      </div>
        <div class= "col-xs-3 col-sm-3", style="padding-top: 20px">
         <%= cl_image_tag @lift.photo, height: 200, width: 200, crop: :fill %>
    </div>

      <div class= "col-xs-9 col-sm-9">
        <div class="card">
          <h3><%= @lift.name%></h3>
          <h5><%= @lift.address%></h5>
        </div>
      </div>

      <div class= "col-xs-3 col-sm-3">
<!--         <%= link_to 'Edit', edit_lift_path(@lift) %> |
        <%= link_to 'Back', lifts_path %> -->
<!--         <p><%= link_to 'Ajouter un nouveau point', new_lift_path(@lift)%></p> -->
      </div>
    </div>
  </div>
</div>
<div class= "wrapper-grey">
  <div class= "container", style="padding-top: 100px; padding-bottom: 100px">
    <div class= "row">
      <div class='col-sm-8'>
        <div class="form-group">
          <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control" />
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>

        <%= week_calendar number_of_weeks: 2 do |date| %>
        <%= date %>
        <% end %>
      </div>
      <div class='offset-1-col-sm-4'>
        <div class="form-group">
          <%= link_to 'Réservez', lifts_path, {class: "btn-medium"}%>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @lift_coordinates %>;
      alert('lift coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= cl_image_tag("garagepourri.jpg",
      width: 400, height: 300, crop: :fill) %>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>L'entretien sans intermédiaire</h1>
    <h1>Louez votre espace de garage</h1>

      <form class="form-inline">
        <div class="form-group">
          <label for="geolocalizeAddress">Votre code postal</label>
            <input type="text" class="form-control" id="geolocalizeAddress" placeholder="59120">
        </div>
      <button type="submit" class="btn btn-default">Valider</button>
      </form>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
 <div class="container">
   <div class="row">

     <div class="col-xs-12 col-sm-4">
       <h4>INFO</h4>
       <ul>
         <li>FAQ</li>
         <li>PRICING</li>
         <li>TERMS OF USE</li>
         <li>PRIVACY</li>
       </ul>
     </div>
     <div class="col-xs-12 col-sm-4">
       <h4>CONTACT</h4>
       <ul>
         <li>PARTNERSHIPS</li>
         <li>MEDIA ENQUIRIES</li>
         <li>SUPPORT@­MINDSPIRIT.COM</li>
         <li>+1 (941) 888-4447</li>
       </ul>
     </div>
     <div class="col-xs-12 col-sm-4">
       <h4>ADDRESS</h4>
       <ul>
         <li>MIND SPIRIT INC.</li>
         <li>500 3RD ST.</li>
         <li>SAN FRANCISCO, CA 94107</li>
       </ul>
     </div>
   </div>
   <div class="col-xs-12">
     <h5 style="text-align: center;">© 2016 MIND SPIRIT INC.</h5>
   </div>
 </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>